### ISSUE TITLE
Implement the rest of misnested tag recovery

### ISSUE THREAD

**Issue by kmcallister** [servo/html5ever#15]
Adoption agency algorithm, foster parenting, reconstruct formatting, etc.

**Comment by aroben** [comment]
Foster parenting is now implemented, right? https://github.com/servo/html5ever/commit/6eb77b2e49a8a05d29977a638dfc9e8adb079302

Looks like there's still a warning and a FIXME about it: https://github.com/servo/html5ever/blob/3d4258abcf9b1d14671088925a350ece64c698ee/src/tree_builder/actions.rs#L401. Are those still valid?

**Comment by aroben** [comment]
I have a branch that implements the adoption agency algorithm and "reconstruct the active formatting elements". I just need to clean up the code and I'll put it in a PR today or tomorrow.

**Comment by kmcallister** [comment]
Wow, that's amazing!

I was not *at all* looking forward to implementing AAA so I'm overjoyed to hear you have it working :)  It seemed I would need a data structure for handling a whole stack of elements with arbitrary "pointers" into it that stay valid even when elements are added/removed.  I'm very interested to see how you implemented it!

**Comment by kmcallister** [comment]
How many tests remain in `data/test/ignore`?

**Comment by aroben** [comment]
> It seemed I would need a data structure for handling a whole stack of elements with arbitrary "pointers" into it that stay valid even when elements are added/removed. I'm very interested to see how you implemented it!

For now I've just done a very naive implementation that scans through the list of active formatting elements looking for the bookmarked node. There are probably a number of inefficiencies in the initial implementation that can be improved, but I figured better to get something working first and then we can profile it to see what's slow.

> How many tests remain in `data/test/ignore`?

The branch removes 87 tests from that file, leaving 37 still listed. (#74 removes two more.) Most of the remaining are failing due to `<ruby>` or `<noscript>` handling. (Obviously there's still the MathML/SVG/`<template>` tests that are getting skipped by other means.)
