### ISSUE TITLE
Macros to generate tree building rules don't work in current Rust

### ISSUE THREAD

**Issue by jdm** [servo/html5ever#216]
Apparently the code was generated long enough ago that rules around writing macros have changed.
```
<pcwalton> ugh, and I can’t rebuild html5ever macros because it’s incompatible with my rustc
<pcwalton> we can’t make changes to the tree building rules because nobody updated the macros to work with current rust
 <jdm> pcwalton: sounds like building those macros should be part of CI
```

**Comment by Ygg01** [comment]
So, this needs to be migrated to `syn` or `syntex`?

**Comment by jdm** [comment]
Either that or find a way to avoid using a compiler plugin entirely.

**Comment by jdm** [comment]
Presumably referring to https://github.com/servo/html5ever/blob/master/macros/src/match_token.rs and https://github.com/servo/html5ever/blob/master/macros/src/pre_expand.rs .

**Comment by Ygg01** [comment]
And if you choose to avoid compiler plugins, you might need to compare https://github.com/servo/html5ever/blob/master/src/tree_builder/rules.rs and  https://github.com/servo/html5ever/blob/master/src/tree_builder/rules.expanded.rs

**Comment by Ygg01** [comment]
Some preliminary findings: 
* `syn` only works on custom derive, if we want to maintain current syntax, we need `syntex`.
*  I initially thought I could convert current rules into macros. Since `tag @ <html> => $expr` essentially turns into a

        TagToken(tag @ Tag {kind: StartTag, name: atom!("html"), .. })) => expr

I thought I could turn it into a similar macro. But alas, not problem is `atom!(stringify!($ident))` requires a procedural macro.

So options to explore are: 
  1) fixup `rules.expanded.rs` into plain Rust, 
  2) write a procedural macro in `syntex`. 

My fear that `syntex` might get discontinued because Macros 1.1 and `syn` will render it obsolete for `serde`.

**Comment by jdm** [comment]
I'll see what the people maintaining syntex think about its future.

**Comment by SimonSapin** [comment]
I’m working on replacing libsyntax’s parsing and quasi-quoting with a simplistic hand-rolled parser and string formatting. A downside is that it is more strict (regarding e.g. whitespace in some places) and provides almost no diagnostics (such as line number) when it encounters unexpected input.

**Comment by SimonSapin** [comment]
It’s ugly, but it works: https://github.com/servo/html5ever/pull/217
