### ISSUE TITLE
Implement PartialEq for RcDom types?

### ISSUE THREAD

**Issue by killercup** [servo/html5ever#281]
For fun, I've been fiddling with a simple fuzzer for html5ever that reads html into an RcDom, writes it out to a string and reads it in for a second time into another RcDom, to then compare the two DOMs.

To not write a huge bunch of helper code, I'd need an implementation PartialEq for Node and NodeData. This is easy to add -- I just needed to write the impl myself for Node to skip the `parent` field (which is a Cell, and that only implements PartialEq when its content implements Copy).

Would you be interested in this? Does skipping parent make sense to you?

(I also implemented Debug that also skips parent, to use it in assert_eq. Spoiler: The output is really long and really unreadable.)

**Comment by SimonSapin** [comment]
Is this "deep" sub-tree comparison rather than node identity by address? The downside is that `==` (compared to a named method) is that it doesn’t say.

More importantly though, `rcdom` mostly exists to enable html5ever to run its own test suite. I’d rather not got down the path of adding many convenience methods to make it nice to use for many different use cases, that’s rather [Kuchiki](https://github.com/kuchiki-rs/kuchiki)’s role. I think deep sub-tree comparison as an appropriately named method (rather than a `PartialEq` impl) would be a nice addition to Kuchiki, if you feel like sending a PR. You might want something like "exact" in the name, with the docs specifying that whitespace in text nodes are compared like other text. By the way, do *you* want whitespace-sensitivity? What do you use this for?

**Comment by killercup** [comment]
> What do you use this for?

Literally only the fuzzer script. And only to see that the read-write-read roundtrip works. Honestly, I was just bored.

> I think deep sub-tree comparison as an appropriately named method (rather than a PartialEq impl) would be a nice addition to Kuchiki, if you feel like sending a PR.

Kuchiki seem nice, but very under-documented. I'll have a look, and maybe send a PR or two :)

**Comment by jdm** [comment]
Since RcDom is now officially an internal-only crate intended for tests, I'm going to go ahead and close this.
