### ISSUE TITLE
Integrate with html-parsers-benchmark

### ISSUE THREAD

**Issue by kmcallister** [servo/html5ever#51]
https://github.com/seriyps/html-parsers-benchmark

I believe @Ygg01 made some progress on this.

We can add Hubbub and Gecko's C++ parser as well.

**Comment by nox** [comment]
@Ygg01 Ping?

**Comment by Ygg01** [comment]
@nox Pong :P Sorry, RL has a way of interfering with best laid plan of mice and men.

Anyway, this been a long time, since I experimented on this, I made it work, but the Rust console output was kinda hard to get to work with what benchmark expected (the lines came out in slightly wrong, non-deterministic order), confusing the hell out of the benchmark tool.

Also a big problem is that it's not Rust friendly tool. It's a collection of bash and python scripts, so running it via `rust bench`, is kinda hard.

To make things worse, the benchmark  wasn't updated in quite a while (Aug 2013).

**Comment by ordian** [comment]
Also, take a look at [myhtml](https://github.com/lexborisov/myhtml) and benchmarks:
[results](https://raw.githubusercontent.com/lexborisov/benchmark-html-persers/master/Results/time/benchmark_0_500.png)
[code](https://github.com/lexborisov/benchmark-html-persers)

Basically, this benchmark evaluates time of parsing TOP500 alexa sites in memory.

parser  | myhtml | gumbo | html5ever
--------- | --------- | -------- | -------------                    
overall time | 0.50890 | 6.12951 | 4.50536
memory | 32120832 | 29319168 | 30715904

**Comment by Ygg01** [comment]
So how do you want this done?

As a shell command that calls different html and parses them? Should we attempt to make our own benchmark or attempt to extend existing benchmarks?

**Comment by nox** [comment]
Closing this for now.
